#!/usr/bin/python2.7
# EASY-INSTALL-ENTRY-SCRIPT: 'cfncluster==1.3.1','console_scripts','cfncluster'
__requires__ = 'cfncluster==1.3.1'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('cfncluster==1.3.1', 'console_scripts', 'cfncluster')()
    )
