#!/usr/bin/python2.7
# EASY-INSTALL-ENTRY-SCRIPT: 'aws-shell==0.1.1','console_scripts','aws-shell-mkindex'
__requires__ = 'aws-shell==0.1.1'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('aws-shell==0.1.1', 'console_scripts', 'aws-shell-mkindex')()
    )
