#!/bin/bash
#
#

argc=$#
if [ ${argc} -ne 1 ] && [ ${argc} -ne 2 ]; then
  echo "The number of input: ${argc}"
  echo "ctrail get"
  echo "ctrail get us-east-1"
  echo "ctrail show all"
  echo "ctrail show UpdateProject"
  echo "ctrail show 0154e36e-fb04-11e6-92d6-2747cb72d53b"
  exit 1
fi

arg1=$1
arg2=$2

if [ ${arg1} == "get" ]; then
   if [ -z ${arg2} ]; then
       reg="ap-southeast-2"
   else
       reg=${arg2}
   fi
   year=$(date '+%Y')
   month=$(date '+%m')
   day=$(date '+%d')
   rm -f *.json > /dev/null
   echo "aws --region ap-southeast-2 s3 cp --recursive s3://aws-inoutomo-logs/AWSLogs/765789999941/CloudTrail/${reg}/${year}/${month}/${day}/ ."
   aws --region ap-southeast-2 s3 cp --recursive s3://aws-inoutomo-logs/AWSLogs/765789999941/CloudTrail/${reg}/${year}/${month}/${day}/ . > /dev/null
   rm -f *.json > /dev/null
   gzip -d *.gz
fi

if [ ${arg1} == "show" ]; then
    if [ -z ${arg2} ] || [ ${arg2} == "all" ]; then
        cat *.json | jq -r '.Records[] | [.eventTime, .eventName, .sourceIPAddress, .requestID, .userIdentity.arn] | @csv' | sort -n
    else
        regexp="^[A-Z]"
        if [[ ${arg2} =~ $regexp ]]; then
            api=${arg2}
            echo "cat *.json | jq -r '.Records[]' | jq -r 'select(.eventName == \"${api}\")'"
            cat *.json | jq -r '.Records[]' | jq -r "select(.eventName == \"${api}\")"
        else
            reqid=${arg2}
            echo "cat *.json | jq -r '.Records[]' | jq -r 'select(.requestID == \"${reqid}\")'"
            cat *.json | jq -r '.Records[]' | jq -r "select(.requestID == \"${reqid}\")"
        fi
    fi
fi

